SET DEFINE OFF;
INSERT	INTO GENRE_TABLE VALUES( 1, 'Action' );
INSERT	INTO GENRE_TABLE VALUES( 2, 'Free to Play' );
INSERT	INTO GENRE_TABLE VALUES( 3, 'RPG' );
INSERT	INTO GENRE_TABLE VALUES( 4, 'Adventure' );
INSERT	INTO GENRE_TABLE VALUES( 5, 'Indie' );
SET DEFINE ON;
